Document: sonic-unis-framework
Title: Debian sonic-unis-framework Manual
Author: <insert document author here>
Abstract: This manual describes what sonic-unis-framework is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sonic-unis-framework/sonic-unis-framework.sgml.gz

Format: postscript
Files: /usr/share/doc/sonic-unis-framework/sonic-unis-framework.ps.gz

Format: text
Files: /usr/share/doc/sonic-unis-framework/sonic-unis-framework.text.gz

Format: HTML
Index: /usr/share/doc/sonic-unis-framework/html/index.html
Files: /usr/share/doc/sonic-unis-framework/html/*.html
